language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r ./src/scrapper/requirements.txt --use-mirrors"
# command to run tests
script: make scrape
branches:
  only:
    - master